//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearnEntities : DbContext
    {
        public LearnEntities()
            : base("name=LearnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<ServiceClients> ServiceClients { get; set; }
        public virtual DbSet<ServicePhotos> ServicePhotos { get; set; }
        public virtual DbSet<Services> Services { get; set; }
    }
}
